services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: sugimotoasahi/portfolio:latest
    container_name: portfolio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/sugimoto-asahi.com/privkey.pem
        target: /etc/ssl/private/sugimoto-asahi.com/privkey.pem

      - type: bind
        source: /etc/letsencrypt/live/sugimoto-asahi.com/fullchain.pem
        target: /etc/ssl/certs/sugimoto-asahi.com/fullchain.pem
